### ISSUE TITLE
Discovery 2: design updates

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-site#111]
<img width="1406" alt="Screen Shot 2021-01-19 at 10 31 30 PM" src="https://user-images.githubusercontent.com/76966798/105214827-5e4cfd00-5b05-11eb-92ff-be854133e79d.png">

-  A common theme here is trying to create some breathing room/white space between text elements (through line height, margin/padding, etc.)
- Graph title: increase line height to 1.5. When I say "increase line height to 1.5," I mean like line-height: 1.5 with no units. When in doubt about how to set that property, that's often a good starting place in my experience. 
- Move "higher / socioeconomic inequality / lower" label a bit to the right to create more space between it and the place labels
- Add space between "Gaps shrinking / Gaps widening" label and "10 year change in white-black achievement gap in grade-level units (2009-2018) label
- Remove "scroll for more" text/functionality

**Comment by alegzandach** [comment]
@laurendoone wondering if we can pull having 'gaps shrinking' and 'gaps widening' becoming flush to the left and right into another ticket? I think it will require some hacky workarounds; echarts doesn't seem to have support for formatting axis names like this and i haven't yet found any examples in the current app or online.

**Comment by laurendoone** [comment]
@alegzandach yep! removed that from this ticket's list and moved to a new ticket assigned to you: https://github.com/Hyperobjekt/seda-site/issues/121
