### ISSUE TITLE
Discovery 2: Add state abbreviation to graph

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-site#113]
Client feedback: We’d prefer to have the state abbreviation on the graph itself if possible

**Comment by alegzandach** [comment]
@laurendoone Should the abbreviation be removed from the tooltip? Or just added to the labels?

**Comment by laurendoone** [comment]
@alegzandach just added to the labels (so it's on the graph and in the tooltip)

**Comment by laurendoone** [comment]
@alegzandach looks like the state abbreviation is now missing from both the graph and the tooltip in staging https://staging.edopportunity.org/discoveries/racial-inequality-predicts-academic-inequality/. can you check on this?
