### ISSUE TITLE
Discovery 1: graph updates

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-site#116]
- Increase the font size of the axis labels
- Lighten the “no change” text so it is lighter than the axis text, rather than the other way around.
- Remove the numbers from the axes (.015 increments)
- Make the image more square to create more space at the bottom below the lowest dot.
- Because the axes will be labeled so clearly after removing the numbers and moving the color bar, we may not need quadrant labels.

**Comment by laurendoone** [comment]
@alegzandach  looks good except we still need to remove the numbers from the graph - do you prefer i open a separate issue for this?

![image](https://user-images.githubusercontent.com/76966798/106054506-fe27ff00-60a0-11eb-8c15-73f78df8791c.png)

**Comment by alegzandach** [comment]
@laurendoone sure, sorry i misunderstood the ticket. So both axis will be without labels?

**Comment by laurendoone** [comment]
@alegzandach correct! though it looks like the x axis already has no numbers, so i guess just remove them from the y axis
