### ISSUE TITLE
Changelog: update design to account for multiple releases

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-site#119]
Feedback from client: there will be at least 2 more releases after 4.0 in the coming months. This page should accommodate multiple releases.

Sean suggests: 
section “New features in the data”
- copy for release 4.2
- copy for release 4.1
- copy for release 4.0
- etc (so newest release is on top)

section "New features in the explorer"
- copy for release 4.2
- copy for release 4.1
- copy for release 4.0

Remove title in header “version 4.0” so it just says “what’s new”

TO DO: @james-minton @sashasashasasha can you provide a mockup of the new design (if needed), or just comment on how the page should look so we can implement?

**Comment by james-minton** [comment]
@laurendoone @sashasashasasha I think this can be accomplished via some text changes on the page, with no redesign needed. Am working on this now.

**Comment by james-minton** [comment]
Interim update: made text and style changes on the staging server today. Remaining: new images/videos.

**Comment by james-minton** [comment]
Closing because I believe this page is future-proofed enough to accommodate updated language for new data versions. Can create issues as those new versions come in.
