### ISSUE TITLE
Discovery 2: add gap numbers to tooltip

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-site#120]
Feedback from client: it would be helpful to show what the gap was in 2009 and in 2018 to give the user more context as to what the cap change means. 

Can we update the tooltip copy to say: Gap in 2009: (number) | Gap in 2018: (number) | Change from 2009-2018: (number)

![Screen Shot 2021-01-21 at 2 13 20 PM](https://user-images.githubusercontent.com/76966798/105419208-2c19c900-5bf3-11eb-81e8-60a0b16a6a05.png)

Do we have all the data needed to show this? Or do we need additional data from the client?

**Comment by laurendoone** [comment]
@james-minton are there other better ways to show this information in the tooltip?

**Comment by alegzandach** [comment]
@laurendoone I don't currently have numbers for 2009 and 2018, only the difference between the two.

**Comment by laurendoone** [comment]
Ok will ask client for the additional data

**Comment by laurendoone** [comment]
@alegzandach  data file is here: https://www.dropbox.com/sh/3uaanlxd5f12bjz/AACO7yK0nwB_OgywOKkZUo7oa/discoveries?dl=0&subfolder_nav_tracking=1

**Comment by laurendoone** [comment]
@alegzandach  while you're in here... can you also update the last line in the tooltip to say (copy change):

• For closing gaps, the last line in the Tooltip should read instead: “At Current Trend, 2009 Gap Will Close in” followed by either a calendar year or “over 100 years” 

• For widening gaps, the last line in the Tooltip should read instead: “At Current Trend, 2009 Gap Will Double in” followed by either a calendar year or “over 100 years” 

this is related to https://github.com/Hyperobjekt/seda-site/issues/114 but since that issue was closed this morning, adding it here instead... or let me know if you want me to open a separate issue
