### ISSUE TITLE
Open new tab when clicking on 'read more' button

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-site#138]
Feedback from client: 

discoveries landing page: it doesn't allow me to open the contents in a new tab with control + click on the "read more" button -- sometimes I find this feature useful to compare different reports addressing similar topics so this might be something to consider

**Comment by lougroshek** [comment]
@laurendoone I can't replicate this on the live site. What is the impetus for reooening?

**Comment by laurendoone** [comment]
Oh I thought I closed it - sorry, was creating a zenhub workspace and moving stuff around to get it prepped for the next release. Closing again
