### ISSUE TITLE
Add new article to "Other Papers Using SEDA" 

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-site#142]
Feedback from client: Here's another paper to add to the "other papers using SEDA", Educational Researcher: https://scholar.harvard.edu/dmq/publications/bias-air-nationwide-exploration-teachers-implicit-racial-attitudes-aggregate-bias

**Comment by james-minton** [comment]
This involves design and I would like to handle. Self-assigning.

**Comment by james-minton** [comment]
Added paper and merged to staging.
