### ISSUE TITLE
Get the Data: add "version 4.0" tab + tables

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-site#155]
For the Feb 3 soft launch, we will not be going live with the latest technical documentation or codebooks (due to client delays). 

TO DO: On the Get The Data page, add a new tab "version 4.0" and add copy "Version 4.0 data coming soon on February 8th"

**Comment by james-minton** [comment]
- [ ] Create provisional "coming soon" tab for 4.0
- [ ] Add 4.0 data tables (awaiting data)

Just merged "coming soon" language to master and staging. Awaiting data for step 2.
