### ISSUE TITLE
Discovery 2: correspond text to chart

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-site#162]
FOR MONDAY FEB 8 RELEASE

Feedback from James: I'm reading Discovery #2 and finding it hard to make correspondences between the places mentioned in the text and the places in the chart. I'm having to work harder than I should to locate them.

Proposed solution: assign numbers to each place in the text and link them to those places in the chart ... e.g. "In Hawaii (shown as ( 1 ) in the chart), the socioeconomic gap ..." etc.

Image below shows what adding the identifiers to the chart might look like:
![image](https://user-images.githubusercontent.com/76966798/106523884-a4f00f00-6496-11eb-8dd2-2921a78ea7db.png)

**Comment by james-minton** [comment]
Edit the first 3 sentences of the last paragraph to read:

> These SES differences predict changes in children’s academic achievement disparities over time. In Dallas, where socioeconomic inequality is high, the academic achievement gap has increased by more than a grade-level in one decade. At this rate, the city's 2009 White-Black achievement gap will double by the year 2027.

**Comment by james-minton** [comment]
The order of and coloration of numbering in the chart should be: 

1) Chicago #F46800
2) Dallas #8C1AF4
3) Hawaii #B2002A

Number font is Sharp Grotesk Medium 20.

James will make copy changes, & Alex can handle placing numbers in the chart.
