### ISSUE TITLE
Get the Data: add copy to version 4.0 tab

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-site#168]
We'll need to add copy to the "version 4.0" tab on the Get The Data page. It should follow the same format as the previous versions.

Sections:

- Intro/Notes - make sure all copy refers to version 4.0 
- Table of contents/anchor links
- Technical Documentation & Codebooks: see spreadsheet "tech docs & codebook" tab - I added the associated links in red text https://docs.google.com/spreadsheets/d/13rMKMoSq9kgbkUyc5Q5qGr77yZPdgLz3v9OkZaYpYqE/edit?usp=sharing
- Test Score Estimations table: see spreadsheet "test score estimates" tab - I added the associated links in red text 
- Covariate Data: see excel spreadsheet "covariates" tab - waiting on links
- Ancillary Data: see excel spreadsheet "ancillary" tab - I added the associated links in red text

**Comment by james-minton** [comment]
Added to staging. May spark further client feedback, but can track myself and feels safe to close the issue.
