### ISSUE TITLE
Discovery 2: add numbers to text to associate to graph

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-site#174]
Feedback from client on discovery 2 -- i like the numbers on chicago, dallas, hawaii (graph)-- but i don't see them referred to in the text (when it mentions chicago, it seems like the text should say something like "see (1) on figure" or something

**Comment by james-minton** [comment]
Guys @laurendoone @alegzandach this has already been done? I did it the weekend before launch: https://edopportunity.org/discoveries/racial-inequality-predicts-academic-inequality/

**Comment by james-minton** [comment]
(Please don't overwrite any work I did on this—I restyled the numbers and rewrote the text and don't want to lose that)

**Comment by laurendoone** [comment]
Oh didn’t see that, thanks! Will let Alex know

**Comment by alegzandach** [comment]
@laurendoone should I remove my assignment to this?
