### ISSUE TITLE
Next / Previous for About page modals

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/seda-site#18]
When advancing through bio modals on `/about`, under certain conditions the progression of bios skips ahead through the sequence.

*To replicate:* 

Click the first bio on `/about`. Advance forward a few steps through the bios using the "next bio" button. You'll see this happens correctly. Then close out of the currently open modal and click on the first bio again, then advance. You will skip ahead in the sequence by however many times you clicked "next bio" the first time around.

The result is essentially that you jump a number of steps with each "next bio," rather than going one by one through the sequence.

This resolves when page is reloaded (and the JS function re-initializes).

*Possible fix?*

Reset the associated JS function to its initial state every time the user closes the modals?

**Comment by amygroshek** [comment]
Pushed a fix for this to master. Event listeners for the prev and next buttons were not being removed, which resulted in each click advancing several steps.
