### ISSUE TITLE
[Copy edits] Methods

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-site#184]
- [x] Change all link references to SEDA technical documentation to link to the 4.1 technical documentation 
     - [Update copy](https://docs.google.com/document/d/1mdY5mCccNHxJni0a5pIQYi9-GNUnRO0e/edit?usp=drive_web&ouid=108947705237145096445&rtpof=true) (links included)

**Comment by ekmason** [comment]
@touchRED Would it be possible to update these numbers to match those on the document? (I've added a screenshot of the change)

![image.png](https://images.zenhubusercontent.com/605b8464e0e66f4aa2b43f51/ff05bd10-c659-4f7e-94fe-27e323a277e4)

I've also noticed that there were a couple more changes that were not highlighted in the copy doc (I went back and highlighted these in green). Would you update the site with these new changes?
