### ISSUE TITLE
Get The Data: New tables & links for 4.1 tab

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-site#186]
- [ ] On the new 4.1 tab, update all the tables and links as outlined in [this spreadsheet](https://docs.google.com/spreadsheets/d/1T5hVhsFIZWMHd8YeUviDWhew2qubM9LG/edit?usp=drive_web&ouid=101771278646720193611&rtpof=true)

**Comment by james-minton** [comment]
I believe this is done on `master`.
