### ISSUE TITLE
New discovery

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-site#195]
## First Draft
- Add new Discovery page
- [Discovery Overview](https://docs.google.com/document/d/14AbxcfqCX0Y2fB0Nk_9C-xTYp8uNmykfRth74Gxoixg/edit)
- Data can be accessed [here](https://www.dropbox.com/s/ju96mze5kxzcnvz/native%20american%20discovery%20data%20for%20HO.csv?dl=0)
- Copy can be found [here](https://docs.google.com/document/d/14AbxcfqCX0Y2fB0Nk_9C-xTYp8uNmykfRth74Gxoixg/edit)

## Second Round of Review
(Full feedback can be found [here](https://docs.google.com/document/d/14AbxcfqCX0Y2fB0Nk_9C-xTYp8uNmykfRth74Gxoixg/edit#))
- [ ] Update copy (use [V3 in doc](https://docs.google.com/document/d/14AbxcfqCX0Y2fB0Nk_9C-xTYp8uNmykfRth74Gxoixg/edit#bookmark=id.7dod9x2g5y92))
- [x] Update graph title to `Learning Rates and Average 3rd Grade Test Scores of Native American Students in U.S. Counties`
- [x] Update axis titles
     - X-axis: `Native American Students’ Average Test Scores in 3rd Grade`
     - Y-axis: `Native American Students’ Learning Rates`
- [x] Update axis labels
     - X-axis: Remove signs from values (Instead of "-5 below", should display "5 below" 
     - Y-axis: use the same labels used in the explorer  (1 = Average, 1.2 = 20% more; .8 = 20% less...etc.)
- [x] Update hover tooltip
     - Use "grade level" instead of "grade-level"
- [x] Bug fix: Discovering a data point via search ensures that it stays highlighted after selection. Update functionality so that a point stays highlighted after a user clicks to select. 
- [ ] Update style to match design (**Sasha to share here**)

## Third round review
- [ ] Change data points in bottom right quadrant to dark green
- [ ] Update suggested citation (update order of contributors)

>Suggested Citation:
>**Fahle, E., Reardon, S. F.** (2021). Learning Rates and Average 3rd Grade Test Scores of Native American Students in U.S. Counties. [Data Discovery by The Educational Opportunity Project]. https://edopportunity.org/discoveries/native-american-students/

**Comment by sashasashasasha** [comment]
Desktop and mobile mockups in Figma in a page called [FINAL MOCKUPS](https://www.figma.com/file/15hzSKjYOAqFqC7hzQEUej/SEDA-Discoveries-and-4.0-updates-DRAFT?node-id=298%3A0)

**Comment by ekmason** [comment]
Citation [copy here](https://docs.google.com/document/d/1zWfC_ufddcmc3Qcy9DIdlso-r3TKes5R/edit)

**Comment by ekmason** [comment]
More changes from second round of client review: 

- Change data points in bottom right quadrant to dark green
- Move visualization to the top of the page


[Full ref doc](https://docs.google.com/document/d/14AbxcfqCX0Y2fB0Nk_9C-xTYp8uNmykfRth74Gxoixg/edit)

**Comment by Lane** [comment]
remaining issues based on [latest preview](https://upbeat-agnesi-507eb4.netlify.app/discoveries/native-american-students/)

- add hero image
- update social image (metadata)
- mobile implementation (see Sasha's mockups)
- add hint text under search when there are no selections (see Sasha's mockups)
- allow keyboard selection of items from search (type letters, press down + up keys to select item, enter to add to selected counties)
- desktop: add scroll overflow to selected counties area when it exceeds the height of the chart
- [discoveries index page](https://upbeat-agnesi-507eb4.netlify.app/discoveries/): update author, add human readable excerpt, add discovery thumbnail
