### ISSUE TITLE
Homepage: flash of unstyled content?

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/seda-site#46]
@amygroshek was trying to convince myself this was a caching issue on my machine, but now suspecting it happens for all users. Are you able to replicate?

Homepage hero shows the full map illustration for a split second before animation runs.

![flash of unstyled content2](https://user-images.githubusercontent.com/33635008/70067348-bd734980-15b3-11ea-9109-4def33b767a0.gif)

**Comment by amygroshek** [comment]
@james-minton Hmmm, interesting. I'm able to replicate but actually not sure it's FOUC because the logos and icons appear to load right away. Looks to me like there's an element in the animated SVG that's not been hidden while the JS is loading.

**Comment by amygroshek** [comment]
@james-minton This is merged into `staging`.

**Comment by james-minton** [comment]
Thanks, looks good! Merging to production.
