### ISSUE TITLE
Edits/additions to existing site copy

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/seda-site#69]
These comprise revisions to existing container site (not Explorer) copy, and include 

- updating outdated references to data years, etc.
- addition of FAQs, glossary items, etc. -- (margins of error may need to be an addition)
- edits to other site copy

Steps:

- [ ] Make edits and add new language in Google doc (SEDA/Hyperobjekt) (finalized by 1/8/2021)
- [ ] Apply these changes to staging site (Hyperobjekt) (by 1/15/2021)
- [ ] Merge live (Hyperobjekt)

**Comment by laurendoone** [comment]
Tracking copy changes in separate issues. Closing this for now.
