### ISSUE TITLE
Discovery 1: Add "-.015" to X axis

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-site#87]
I see the potential issues here, but would it be possible to make it so the -.015 was appearing on both the x and y axes, instead of just the X?

![image](https://user-images.githubusercontent.com/76966798/104231843-6077d300-5404-11eb-8b5e-17462d14e16e.png)

**Comment by alegzandach** [comment]
Here's a sample fix. I've made the min index of the xaxis -0.016, incremented by .001, and made the labels that are currently appearing the only ones allowed to appear. There doesn't seem to be a way to apply this kind of restriction to axis ticks, so I've removed axis ticks. Is this an acceptable solution? 

![samplefix15](https://user-images.githubusercontent.com/12611947/104637503-dd0fe900-5672-11eb-95f2-54745a920606.JPG)

**Comment by laurendoone** [comment]
@alegzandach should be fine, we'll see what the client says when they review :)
